import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "prod_001",
    slug: "hospitality-concierge-ai",
    name: "Hospitality Concierge AI",
    shortDescription:
      "Multilingual AI guest assistant for hotels, resorts, and vacation rentals.",
    fullDescription:
      "Hospitality Concierge AI is a 24/7 AI assistant that handles guest inquiries, booking questions, local recommendations, and upsell opportunities — in Papiamentu, Spanish, English, and Dutch. Deployed as a chatbot on your website or WhatsApp channel, it reduces front-desk workload while elevating the guest experience. Built specifically for Caribbean hospitality businesses that serve diverse international guests.",
    category: "hospitality",
    priceCents: 29700,
    billingType: "monthly",
    featured: true,
    status: "active",
    capabilities: [
      "24/7 multilingual guest support (Papiamentu, Spanish, English, Dutch)",
      "Automated check-in / check-out FAQ handling",
      "Local attractions and dining recommendations",
      "Room upgrade and amenity upsell prompts",
      "Booking inquiry routing to front desk",
      "WhatsApp and web chat deployment",
      "Monthly performance summary report",
    ],
    idealFor: [
      "Boutique hotels and resorts in Curaçao and the Caribbean",
      "Vacation rental operators with international guests",
      "Hotel chains seeking to reduce front-desk call volume",
      "Hospitality groups managing multiple properties",
    ],
    imagePath: "/images/products/hospitality-concierge-ai.jpg",
    ctaLabel: "Request This Product",
  },
  {
    id: "prod_002",
    slug: "property-scout-ai",
    name: "Property Scout AI",
    shortDescription:
      "AI-powered property matching and lead qualification for real estate agents.",
    fullDescription:
      "Property Scout AI automates the most time-consuming parts of real estate sales: qualifying new leads, matching buyers to listings, generating multilingual property descriptions, and following up with prospects automatically. Agents receive qualified, conversation-ready leads while the AI handles initial screening and listing presentations — in English, Spanish, Dutch, and Papiamentu.",
    category: "real-estate",
    priceCents: 19700,
    billingType: "monthly",
    featured: true,
    status: "active",
    capabilities: [
      "Automated buyer lead qualification via chat or form",
      "AI property matching based on budget, location, and preferences",
      "Multilingual listing descriptions (EN / ES / NL / PAP)",
      "Automated follow-up sequences for cold and warm leads",
      "Comparative market summary generation",
      "Integration with WhatsApp for instant lead engagement",
      "Weekly lead pipeline digest",
    ],
    idealFor: [
      "Independent real estate agents in Curaçao and Aruba",
      "Real estate agencies managing large listing portfolios",
      "Property developers marketing new builds internationally",
      "Investment property advisors handling international buyers",
    ],
    imagePath: "/images/products/property-scout-ai.jpg",
    ctaLabel: "Request This Product",
  },
  {
    id: "prod_003",
    slug: "contentflow-ai",
    name: "ContentFlow AI",
    shortDescription:
      "AI content engine for social media, email, and multilingual marketing copy.",
    fullDescription:
      "ContentFlow AI takes your brand voice, products, and calendar and turns them into a consistent stream of social media posts, email campaigns, landing page copy, and ad creatives — in multiple languages. No more blank-page paralysis or inconsistent messaging. Built for entrepreneurs and marketing teams who need high-volume, on-brand content without hiring a large creative team.",
    category: "marketing",
    priceCents: 14700,
    billingType: "monthly",
    featured: false,
    status: "active",
    capabilities: [
      "Weekly social media content calendar (LinkedIn, Instagram, Facebook)",
      "Multilingual copy generation (English, Spanish, Dutch, Papiamentu)",
      "Email newsletter drafts with subject line variants",
      "Product launch announcement packages",
      "Ad creative copywriting for Meta and Google",
      "Brand voice training from existing content",
      "SEO-optimised blog post outlines",
    ],
    idealFor: [
      "SME owners who need consistent content without a full marketing team",
      "Marketing managers in bilingual or multilingual markets",
      "E-commerce brands targeting Curaçao and Latin American markets",
      "Agencies managing content for multiple clients",
    ],
    imagePath: "/images/products/contentflow-ai.jpg",
    ctaLabel: "Request This Product",
  },
  {
    id: "prod_004",
    slug: "operations-command-gpt",
    name: "Operations Command GPT",
    shortDescription:
      "AI business operations assistant for reporting, documentation, and process automation.",
    fullDescription:
      "Operations Command GPT is an internal AI assistant that helps business owners and managers run tighter operations. It drafts SOPs, summarises meetings, generates weekly reports from raw data, answers team questions from your internal knowledge base, and routes recurring tasks automatically. It acts as an always-on chief-of-staff layer for growing businesses that are not yet ready to hire one.",
    category: "business-operations",
    priceCents: 39700,
    billingType: "monthly",
    featured: true,
    status: "active",
    capabilities: [
      "SOP and policy document drafting from verbal or written input",
      "Meeting transcript summarisation with action item extraction",
      "Weekly business performance report generation",
      "Internal knowledge base Q&A for team members",
      "Recurring task routing and reminder automation",
      "Onboarding document generation for new hires",
      "Decision log capture and retrieval",
    ],
    idealFor: [
      "Business owners managing 5–50 person teams",
      "Operations managers drowning in manual reporting",
      "Companies standardising processes before scaling",
      "Remote teams that need consistent documentation",
    ],
    imagePath: "/images/products/operations-command-gpt.jpg",
    ctaLabel: "Request This Product",
  },
  {
    id: "prod_005",
    slug: "coursebuilder-ai",
    name: "CourseBuilder AI",
    shortDescription:
      "AI-powered course design and content generation for trainers and educators.",
    fullDescription:
      "CourseBuilder AI helps trainers, educators, and HR teams build structured learning content in a fraction of the time. Provide a topic, audience, and learning objectives, and CourseBuilder AI generates full course outlines, module scripts, quiz questions, exercises, and slide briefs. Content can be produced in multiple languages to serve multilingual learner groups across the Caribbean and Latin America.",
    category: "education",
    priceCents: 9700,
    billingType: "monthly",
    featured: false,
    status: "active",
    capabilities: [
      "Full course outline generation from a topic brief",
      "Module-by-module script and lesson content drafting",
      "Quiz and assessment question generation",
      "Practical exercise and case study creation",
      "Slide deck brief and speaker notes",
      "Multilingual content adaptation",
      "Learning objective alignment review",
    ],
    idealFor: [
      "Corporate trainers and L&D managers",
      "Independent educators building online courses",
      "HR departments developing onboarding programmes",
      "Schools and universities creating supplemental content",
    ],
    imagePath: "/images/products/coursebuilder-ai.jpg",
    ctaLabel: "Request This Product",
  },
  {
    id: "prod_006",
    slug: "agent-deployment-pack",
    name: "Agent Deployment Pack",
    shortDescription:
      "Bespoke multi-agent AI system design, build, and deployment for your business.",
    fullDescription:
      "The Agent Deployment Pack is a done-for-you engagement where GPT Innovation by Attaf designs, builds, and deploys a custom multi-agent AI system tailored to your specific business workflows. This covers everything from requirements gathering and agent architecture to integration with your existing tools, testing, deployment, and a 30-day post-launch support period. Pricing is scoped to your requirements.",
    category: "ai-automation",
    priceCents: 0,
    billingType: "custom",
    featured: true,
    status: "active",
    capabilities: [
      "Requirements gathering and business process mapping",
      "Custom agent architecture design",
      "Agent development and prompt engineering",
      "Integration with CRM, WhatsApp, Notion, Supabase, or your stack",
      "End-to-end testing and quality assurance",
      "Deployment to production environment",
      "30-day post-launch monitoring and support",
    ],
    idealFor: [
      "Businesses with complex, high-value workflows to automate",
      "Founders who want AI capabilities without hiring an AI team",
      "Enterprises piloting AI automation before internal investment",
      "Agencies wanting a white-label AI delivery partner",
    ],
    imagePath: "/images/products/agent-deployment-pack.jpg",
    ctaLabel: "Request a Custom Quote",
  },
  {
    id: "prod_007",
    slug: "proposal-generator-pro",
    name: "Proposal Generator Pro",
    shortDescription:
      "One-time AI setup that produces professional client proposals in minutes.",
    fullDescription:
      "Proposal Generator Pro is a configured AI assistant that generates polished, on-brand client proposals from a simple briefing form. Fill in the client name, project scope, deliverables, and pricing — and receive a ready-to-send proposal document in your brand voice. One-time setup fee covers brand voice training, template configuration, and three revision cycles. Delivered as a private GPT or workflow tool.",
    category: "business-operations",
    priceCents: 49700,
    billingType: "one-time",
    featured: false,
    status: "active",
    capabilities: [
      "Brand voice and tone configuration",
      "Service package and pricing template setup",
      "One-click proposal generation from a briefing form",
      "Executive summary, scope, timeline, and pricing sections",
      "Client-specific personalisation fields",
      "Export to PDF or Google Docs",
      "Three rounds of post-delivery revisions",
    ],
    idealFor: [
      "Consultants and freelancers writing proposals regularly",
      "Agencies who lose deals due to slow proposal turnaround",
      "Service businesses standardising their sales documents",
      "Solo founders who want professional materials without a designer",
    ],
    imagePath: "/images/products/proposal-generator-pro.jpg",
    ctaLabel: "Request This Product",
  },
  {
    id: "prod_008",
    slug: "multilingual-sales-bot",
    name: "Multilingual Sales Bot",
    shortDescription:
      "AI sales assistant in Papiamentu, Spanish, English, and Dutch for Caribbean B2B teams.",
    fullDescription:
      "Multilingual Sales Bot is a conversational AI deployed on your website or WhatsApp channel that qualifies inbound B2B leads, answers product and pricing questions, books discovery calls, and hands off warm prospects to your sales team — in whichever language the prospect prefers. Purpose-built for Curaçao and Caribbean markets where Papiamentu, Dutch, Spanish, and English are all in active use.",
    category: "marketing",
    priceCents: 19700,
    billingType: "monthly",
    featured: false,
    status: "active",
    capabilities: [
      "Inbound B2B lead qualification in four languages",
      "Automated product and pricing FAQ responses",
      "Discovery call booking via Calendly or WhatsApp",
      "Warm lead handoff with conversation summary",
      "Papiamentu language support (rare in AI products)",
      "CRM integration for lead capture",
      "Monthly lead quality and volume report",
    ],
    idealFor: [
      "B2B companies in Curaçao serving multilingual clients",
      "Caribbean-based SaaS and services businesses",
      "Sales teams that lose leads due to language gaps",
      "Businesses targeting Dutch, Spanish, and Papiamentu-speaking markets",
    ],
    imagePath: "/images/products/multilingual-sales-bot.jpg",
    ctaLabel: "Request This Product",
  },
];
